# Generated by Django 2.2.28 on 2024-11-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='etat',
            new_name='humeur',
        ),
    ]
