# Generated by Django 2.2.28 on 2024-11-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241121_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='humeur',
            new_name='etat',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
